name: "SMZDM Checkin"

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '05 00 * * *'
  watch:
    types: [started]

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19        

    - name: Checkin
      env:
        GO111MODULE: "on"
        SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
        QMSGKEY: ${{ secrets.QMSGKEY }}
      run: go build -o checkin checkin.go && ./checkin
